Pinning SQLAlchemy to 2.0.x
SQLAlchemy-Utils does not have support for SQLAlchemy v2.1 yet
causing issues while importing
https://github.com/kvesteri/sqlalchemy-utils/issues/829
https://github.com/kvesteri/sqlalchemy-utils/issues/800
Should be solved by: https://github.com/kvesteri/sqlalchemy-utils/pull/831

SQLAlchemy on 2.1 is causing this issue during db init:
Traceback (most recent call last):
  File "/opt/dci-control-server/bin/dci-dbinit", line 27, in <module>
    from sqlalchemy_utils import functions as sa_funcs
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy_utils/__init__.py", line 46, in <module>
    from .generic import generic_relationship  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy_utils/generic.py", line 15, in <module>
    class GenericAttributeImpl(attributes.ScalarAttributeImpl):
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'sqlalchemy.orm.attributes' has no attribute 'ScalarAttributeImpl'. Did you mean: '_ScalarAttributeImpl'?
Unable to init the DB. Exiting.